# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'GaoDeTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'AMap3DMap'            #3D地图SDK
    pod 'AMapSearch'           #地图SDK搜索功能
    pod 'AMapLocation'         #定位SDK
    pod 'SDWebImage'

end
